# Site
name: "Working Women's Kitchen"
description: 'Culinary adeventures of two working women'
logo: 'assets/images/wwwk-logo.svg'
baseurl: ''
avatar: 'assets/images/workingwomenskitchen.jpg'
disqus: 'workingwomenskitchen'
email: 'dipti@workingwomenskitchen.com'

include: ['_pages']
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Defaults
defaults:
  # all posts
  - scope:
      path: '_posts'
    values:
      layout: post

  # all pages
  - scope:
      path: '_pages'
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 20
paginate_path: '/pages/:num/'

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.markdown,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
  ]
